# Generated by Django 6.0.5 on 2026-05-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenants', '0005_tenant_license_activated_tenant_license_expiry_and_more'),
        ('users', '0002_alter_user_tenant'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_tenant__b5ba35_idx',
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tenant'], name='users_user_tenant__79c011_idx'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
