# Generated by Django 6.0.7 on 2026-07-18 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0013_alter_device_unique_together_and_more'),
        ('users', '0003_remove_user_users_user_tenant__b5ba35_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_tenant__79c011_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='tenants.facility'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='tenant',
        ),
    ]
