# Generated by Django 6.0.5 on 2026-05-30 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feescheduleitem',
            options={'ordering': ['procedure__code']},
        ),
    ]
