# Generated by Django 6.0.7 on 2026-07-18 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorization',
            name='exam_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='authorization', to='orders.examorder'),
        ),
        migrations.AddField(
            model_name='claim',
            name='primary_claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_claims', to='billing.claim'),
        ),
        migrations.AddField(
            model_name='claimappeal',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appeals', to='billing.claim'),
        ),
    ]
