# Generated by Django 5.2.14 on 2026-06-04 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('orders', '0001_initial'),
        ('patients', '0001_initial'),
        ('tenants', '0008_alter_modality_code_alter_modality_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='authorization',
            name='exam_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='authorization', to='orders.examorder'),
        ),
        migrations.AddField(
            model_name='authorization',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='claim',
            name='primary_claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_claims', to='billing.claim'),
        ),
        migrations.AddField(
            model_name='claim',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='claimappeal',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appeals', to='billing.claim'),
        ),
        migrations.AddField(
            model_name='claimappeal',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='claimappeal',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='claimline',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.claim'),
        ),
        migrations.AddField(
            model_name='claimappeal',
            name='claim_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appeals', to='billing.claimline'),
        ),
        migrations.AddField(
            model_name='clearinghouse',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='denialreason',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='feeschedule',
            name='modality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.modality'),
        ),
        migrations.AddField(
            model_name='feeschedule',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='feescheduleitem',
            name='fee_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.feeschedule'),
        ),
        migrations.AddField(
            model_name='feescheduleitem',
            name='modality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.modality'),
        ),
        migrations.AddField(
            model_name='insurancepayer',
            name='clearinghouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.clearinghouse'),
        ),
        migrations.AddField(
            model_name='insurancepayer',
            name='fee_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.feeschedule'),
        ),
        migrations.AddField(
            model_name='insurancepayer',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='feeschedule',
            name='payer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_schedules', to='billing.insurancepayer'),
        ),
        migrations.AddField(
            model_name='claim',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.insurancepayer'),
        ),
        migrations.AddField(
            model_name='patientaccount',
            name='guarantor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guaranteed_accounts', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='patientaccount',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_account', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='patientaccount',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='claim',
            name='patient_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='billing.patientaccount'),
        ),
        migrations.AddField(
            model_name='patientinsurance',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='patientinsurance',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.insurancepayer'),
        ),
        migrations.AddField(
            model_name='patientinsurance',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='patientstatement',
            name='patient_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statements', to='billing.patientaccount'),
        ),
        migrations.AddField(
            model_name='patientstatement',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='payment',
            name='patient_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.patientaccount'),
        ),
        migrations.AddField(
            model_name='payment',
            name='received_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='billing.payment'),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='claim_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_details', to='billing.claimline'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='patient_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_plans', to='billing.patientaccount'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='paymentplaninstallment',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.payment'),
        ),
        migrations.AddField(
            model_name='paymentplaninstallment',
            name='payment_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='billing.paymentplan'),
        ),
        migrations.AddField(
            model_name='paymentposting',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_postings', to='billing.claim'),
        ),
        migrations.AddField(
            model_name='paymentposting',
            name='payer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.insurancepayer'),
        ),
        migrations.AddField(
            model_name='paymentposting',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentposting',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='payment_posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='billing.paymentposting'),
        ),
        migrations.AddField(
            model_name='serviceline',
            name='claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_lines', to='billing.claim'),
        ),
        migrations.AddField(
            model_name='serviceline',
            name='exam_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_lines', to='orders.examorder'),
        ),
        migrations.AddField(
            model_name='serviceline',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.facility'),
        ),
        migrations.AddField(
            model_name='serviceline',
            name='patient_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_lines', to='billing.patientaccount'),
        ),
        migrations.AddField(
            model_name='serviceline',
            name='rendering_provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendered_services', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceline',
            name='supervising_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceline',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='service_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.serviceline'),
        ),
        migrations.AddField(
            model_name='claimline',
            name='service_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim_lines', to='billing.serviceline'),
        ),
        migrations.AddIndex(
            model_name='authorization',
            index=models.Index(fields=['tenant', 'status'], name='billing_aut_tenant__18f5ea_idx'),
        ),
        migrations.AddIndex(
            model_name='authorization',
            index=models.Index(fields=['auth_number'], name='billing_aut_auth_nu_6cd55f_idx'),
        ),
        migrations.AddIndex(
            model_name='claimappeal',
            index=models.Index(fields=['tenant', 'status'], name='billing_cla_tenant__bc197d_idx'),
        ),
        migrations.AddIndex(
            model_name='claimappeal',
            index=models.Index(fields=['appeal_number'], name='billing_cla_appeal__e4e935_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='denialreason',
            unique_together={('tenant', 'code_system', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='feescheduleitem',
            unique_together={('fee_schedule', 'procedure_code')},
        ),
        migrations.AddIndex(
            model_name='insurancepayer',
            index=models.Index(fields=['tenant', 'payer_type'], name='billing_ins_tenant__e68992_idx'),
        ),
        migrations.AddIndex(
            model_name='insurancepayer',
            index=models.Index(fields=['tenant', 'is_active'], name='billing_ins_tenant__84c656_idx'),
        ),
        migrations.AddIndex(
            model_name='feeschedule',
            index=models.Index(fields=['tenant', 'schedule_type'], name='billing_fee_tenant__e8721a_idx'),
        ),
        migrations.AddIndex(
            model_name='feeschedule',
            index=models.Index(fields=['tenant', 'is_active'], name='billing_fee_tenant__4fe3fc_idx'),
        ),
        migrations.AddIndex(
            model_name='patientaccount',
            index=models.Index(fields=['tenant', 'account_status'], name='billing_pat_tenant__679608_idx'),
        ),
        migrations.AddIndex(
            model_name='patientaccount',
            index=models.Index(fields=['current_balance'], name='billing_pat_current_8b380c_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['tenant', 'status'], name='billing_cla_tenant__21a4c9_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['tenant', 'submission_date'], name='billing_cla_tenant__e3b54c_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['claim_number'], name='billing_cla_claim_n_322af2_idx'),
        ),
        migrations.AddIndex(
            model_name='patientinsurance',
            index=models.Index(fields=['tenant', 'patient', 'priority'], name='billing_pat_tenant__e153e0_idx'),
        ),
        migrations.AddIndex(
            model_name='patientinsurance',
            index=models.Index(fields=['tenant', 'policy_number'], name='billing_pat_tenant__c8f469_idx'),
        ),
        migrations.AddIndex(
            model_name='patientstatement',
            index=models.Index(fields=['tenant', 'status'], name='billing_pat_tenant__d9bdc4_idx'),
        ),
        migrations.AddIndex(
            model_name='patientstatement',
            index=models.Index(fields=['statement_date'], name='billing_pat_stateme_cacc05_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tenant', 'payment_date'], name='billing_pay_tenant__afafe2_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_method'], name='billing_pay_payment_715e62_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentplan',
            index=models.Index(fields=['tenant', 'status'], name='billing_pay_tenant__403c48_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentplaninstallment',
            unique_together={('payment_plan', 'installment_number')},
        ),
        migrations.AddIndex(
            model_name='paymentposting',
            index=models.Index(fields=['tenant', 'status'], name='billing_pay_tenant__43346e_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentposting',
            index=models.Index(fields=['posting_date'], name='billing_pay_posting_6c1062_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceline',
            index=models.Index(fields=['tenant', 'billing_status'], name='billing_ser_tenant__3622c2_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceline',
            index=models.Index(fields=['tenant', 'service_date'], name='billing_ser_tenant__037275_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceline',
            index=models.Index(fields=['procedure_code'], name='billing_ser_procedu_966e8b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='claimline',
            unique_together={('claim', 'line_number')},
        ),
    ]
