# Generated by Django 6.0.7 on 2026-07-18 12:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
        ('orders', '0002_examorder_deleted_at_examorder_is_deleted_and_more'),
        ('patients', '0003_remove_patient_unique_mrn_per_tenant_and_more'),
        ('tenants', '0012_merge_20260714_0025'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='authorization',
            name='billing_aut_tenant__18f5ea_idx',
        ),
        migrations.RemoveIndex(
            model_name='claim',
            name='billing_cla_tenant__21a4c9_idx',
        ),
        migrations.RemoveIndex(
            model_name='claim',
            name='billing_cla_tenant__e3b54c_idx',
        ),
        migrations.RemoveIndex(
            model_name='claimappeal',
            name='billing_cla_tenant__bc197d_idx',
        ),
        migrations.RemoveIndex(
            model_name='feeschedule',
            name='billing_fee_tenant__e8721a_idx',
        ),
        migrations.RemoveIndex(
            model_name='feeschedule',
            name='billing_fee_tenant__4fe3fc_idx',
        ),
        migrations.RemoveIndex(
            model_name='insurancepayer',
            name='billing_ins_tenant__e68992_idx',
        ),
        migrations.RemoveIndex(
            model_name='insurancepayer',
            name='billing_ins_tenant__84c656_idx',
        ),
        migrations.RemoveIndex(
            model_name='patientaccount',
            name='billing_pat_tenant__679608_idx',
        ),
        migrations.RemoveIndex(
            model_name='patientinsurance',
            name='billing_pat_tenant__e153e0_idx',
        ),
        migrations.RemoveIndex(
            model_name='patientinsurance',
            name='billing_pat_tenant__c8f469_idx',
        ),
        migrations.RemoveIndex(
            model_name='patientstatement',
            name='billing_pat_tenant__d9bdc4_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='billing_pay_tenant__afafe2_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymentplan',
            name='billing_pay_tenant__403c48_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymentposting',
            name='billing_pay_tenant__43346e_idx',
        ),
        migrations.RemoveIndex(
            model_name='serviceline',
            name='billing_ser_tenant__3622c2_idx',
        ),
        migrations.RemoveIndex(
            model_name='serviceline',
            name='billing_ser_tenant__037275_idx',
        ),
        migrations.AlterUniqueTogether(
            name='denialreason',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='clearinghouse',
            name='tenant',
        ),
        migrations.AddIndex(
            model_name='authorization',
            index=models.Index(fields=['status'], name='billing_aut_status_cf94a5_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['status'], name='billing_cla_status_aea0b1_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['submission_date'], name='billing_cla_submiss_d21634_idx'),
        ),
        migrations.AddIndex(
            model_name='claimappeal',
            index=models.Index(fields=['status'], name='billing_cla_status_6a5aec_idx'),
        ),
        migrations.AddIndex(
            model_name='feeschedule',
            index=models.Index(fields=['schedule_type'], name='billing_fee_schedul_edadb1_idx'),
        ),
        migrations.AddIndex(
            model_name='feeschedule',
            index=models.Index(fields=['is_active'], name='billing_fee_is_acti_a44cbc_idx'),
        ),
        migrations.AddIndex(
            model_name='insurancepayer',
            index=models.Index(fields=['payer_type'], name='billing_ins_payer_t_3d4d2b_idx'),
        ),
        migrations.AddIndex(
            model_name='insurancepayer',
            index=models.Index(fields=['is_active'], name='billing_ins_is_acti_5b6902_idx'),
        ),
        migrations.AddIndex(
            model_name='patientaccount',
            index=models.Index(fields=['account_status'], name='billing_pat_account_0e774f_idx'),
        ),
        migrations.AddIndex(
            model_name='patientinsurance',
            index=models.Index(fields=['patient', 'priority'], name='billing_pat_patient_1f3b54_idx'),
        ),
        migrations.AddIndex(
            model_name='patientinsurance',
            index=models.Index(fields=['policy_number'], name='billing_pat_policy__9a52c7_idx'),
        ),
        migrations.AddIndex(
            model_name='patientstatement',
            index=models.Index(fields=['status'], name='billing_pat_status_a7a67f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='billing_pay_payment_bed741_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentplan',
            index=models.Index(fields=['status'], name='billing_pay_status_6f2ac2_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentposting',
            index=models.Index(fields=['status'], name='billing_pay_status_6205f4_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceline',
            index=models.Index(fields=['billing_status'], name='billing_ser_billing_1c6ced_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceline',
            index=models.Index(fields=['service_date'], name='billing_ser_service_e59cad_idx'),
        ),
        migrations.RemoveField(
            model_name='authorization',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='claimappeal',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='feeschedule',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='insurancepayer',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='patientaccount',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='patientinsurance',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='patientstatement',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='paymentplan',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='paymentposting',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='serviceline',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='denialreason',
            name='tenant',
        ),
    ]
