# Generated by Django 6.0.5 on 2026-05-30 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_feescheduleitem_options'),
        ('orders', '0006_procedure'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feescheduleitem',
            unique_together={('fee_schedule', 'procedure')},
        ),
        migrations.AddField(
            model_name='feescheduleitem',
            name='procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_schedule_items', to='orders.procedure'),
        ),
        migrations.RemoveField(
            model_name='feescheduleitem',
            name='modality',
        ),
        migrations.RemoveField(
            model_name='feescheduleitem',
            name='procedure_code',
        ),
        migrations.RemoveField(
            model_name='feescheduleitem',
            name='procedure_description',
        ),
        migrations.RemoveField(
            model_name='feescheduleitem',
            name='revenue_code',
        ),
    ]
