# Generated by Django 6.0.5 on 2026-05-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_payer_management_enhancements'),
        ('tenants', '0008_alter_modality_code_alter_modality_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clearinghouse',
            options={'ordering': ['name']},
        ),
        migrations.RenameIndex(
            model_name='clearinghouse',
            new_name='billing_cle_code_700066_idx',
            old_name='billing_cle_code_idx',
        ),
        migrations.RenameIndex(
            model_name='insurancepayer',
            new_name='billing_ins_code_b0ef41_idx',
            old_name='billing_ins_code_idx',
        ),
        migrations.RenameIndex(
            model_name='insurancepayer',
            new_name='billing_ins_edi_ena_328765_idx',
            old_name='billing_ins_edi_en_idx',
        ),
        migrations.AddIndex(
            model_name='clearinghouse',
            index=models.Index(fields=['tenant', 'is_active'], name='billing_cle_tenant__6e7d79_idx'),
        ),
    ]
