# Generated by Django 6.0.7 on 2026-07-18 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_initial'),
        ('orders', '0001_initial'),
        ('patients', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='claimappeal',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='claimline',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.claim'),
        ),
        migrations.AddField(
            model_name='claimappeal',
            name='claim_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appeals', to='billing.claimline'),
        ),
        migrations.AddField(
            model_name='feeschedule',
            name='modality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.modality'),
        ),
        migrations.AddField(
            model_name='feescheduleitem',
            name='fee_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.feeschedule'),
        ),
        migrations.AddField(
            model_name='feescheduleitem',
            name='modality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.modality'),
        ),
        migrations.AddField(
            model_name='insurancepayer',
            name='clearinghouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.clearinghouse'),
        ),
        migrations.AddField(
            model_name='insurancepayer',
            name='fee_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.feeschedule'),
        ),
        migrations.AddField(
            model_name='feeschedule',
            name='payer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_schedules', to='billing.insurancepayer'),
        ),
        migrations.AddField(
            model_name='claim',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.insurancepayer'),
        ),
        migrations.AddField(
            model_name='patientaccount',
            name='guarantor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guaranteed_accounts', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='patientaccount',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_account', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='claim',
            name='patient_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='billing.patientaccount'),
        ),
        migrations.AddField(
            model_name='patientinsurance',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='patientinsurance',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.insurancepayer'),
        ),
        migrations.AddField(
            model_name='patientstatement',
            name='patient_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statements', to='billing.patientaccount'),
        ),
        migrations.AddField(
            model_name='payment',
            name='patient_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.patientaccount'),
        ),
        migrations.AddField(
            model_name='payment',
            name='received_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='billing.payment'),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='claim_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_details', to='billing.claimline'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='patient_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_plans', to='billing.patientaccount'),
        ),
        migrations.AddField(
            model_name='paymentplaninstallment',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.payment'),
        ),
        migrations.AddField(
            model_name='paymentplaninstallment',
            name='payment_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='billing.paymentplan'),
        ),
        migrations.AddField(
            model_name='paymentposting',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_postings', to='billing.claim'),
        ),
        migrations.AddField(
            model_name='paymentposting',
            name='payer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.insurancepayer'),
        ),
        migrations.AddField(
            model_name='paymentposting',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='payment_posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='billing.paymentposting'),
        ),
        migrations.AddField(
            model_name='serviceline',
            name='claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_lines', to='billing.claim'),
        ),
        migrations.AddField(
            model_name='serviceline',
            name='exam_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_lines', to='orders.examorder'),
        ),
        migrations.AddField(
            model_name='serviceline',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.facility'),
        ),
        migrations.AddField(
            model_name='serviceline',
            name='patient_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_lines', to='billing.patientaccount'),
        ),
        migrations.AddField(
            model_name='serviceline',
            name='rendering_provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendered_services', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceline',
            name='supervising_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='service_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.serviceline'),
        ),
        migrations.AddField(
            model_name='claimline',
            name='service_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim_lines', to='billing.serviceline'),
        ),
        migrations.AddIndex(
            model_name='authorization',
            index=models.Index(fields=['status'], name='billing_aut_status_cf94a5_idx'),
        ),
        migrations.AddIndex(
            model_name='authorization',
            index=models.Index(fields=['auth_number'], name='billing_aut_auth_nu_6cd55f_idx'),
        ),
        migrations.AddIndex(
            model_name='claimappeal',
            index=models.Index(fields=['status'], name='billing_cla_status_6a5aec_idx'),
        ),
        migrations.AddIndex(
            model_name='claimappeal',
            index=models.Index(fields=['appeal_number'], name='billing_cla_appeal__e4e935_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='feescheduleitem',
            unique_together={('fee_schedule', 'procedure_code')},
        ),
        migrations.AddIndex(
            model_name='insurancepayer',
            index=models.Index(fields=['payer_type'], name='billing_ins_payer_t_3d4d2b_idx'),
        ),
        migrations.AddIndex(
            model_name='insurancepayer',
            index=models.Index(fields=['is_active'], name='billing_ins_is_acti_5b6902_idx'),
        ),
        migrations.AddIndex(
            model_name='feeschedule',
            index=models.Index(fields=['schedule_type'], name='billing_fee_schedul_edadb1_idx'),
        ),
        migrations.AddIndex(
            model_name='feeschedule',
            index=models.Index(fields=['is_active'], name='billing_fee_is_acti_a44cbc_idx'),
        ),
        migrations.AddIndex(
            model_name='patientaccount',
            index=models.Index(fields=['account_status'], name='billing_pat_account_0e774f_idx'),
        ),
        migrations.AddIndex(
            model_name='patientaccount',
            index=models.Index(fields=['current_balance'], name='billing_pat_current_8b380c_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['status'], name='billing_cla_status_aea0b1_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['submission_date'], name='billing_cla_submiss_d21634_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['claim_number'], name='billing_cla_claim_n_322af2_idx'),
        ),
        migrations.AddIndex(
            model_name='patientinsurance',
            index=models.Index(fields=['patient', 'priority'], name='billing_pat_patient_1f3b54_idx'),
        ),
        migrations.AddIndex(
            model_name='patientinsurance',
            index=models.Index(fields=['policy_number'], name='billing_pat_policy__9a52c7_idx'),
        ),
        migrations.AddIndex(
            model_name='patientstatement',
            index=models.Index(fields=['status'], name='billing_pat_status_a7a67f_idx'),
        ),
        migrations.AddIndex(
            model_name='patientstatement',
            index=models.Index(fields=['statement_date'], name='billing_pat_stateme_cacc05_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='billing_pay_payment_bed741_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_method'], name='billing_pay_payment_715e62_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentplan',
            index=models.Index(fields=['status'], name='billing_pay_status_6f2ac2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentplaninstallment',
            unique_together={('payment_plan', 'installment_number')},
        ),
        migrations.AddIndex(
            model_name='paymentposting',
            index=models.Index(fields=['status'], name='billing_pay_status_6205f4_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentposting',
            index=models.Index(fields=['posting_date'], name='billing_pay_posting_6c1062_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceline',
            index=models.Index(fields=['billing_status'], name='billing_ser_billing_1c6ced_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceline',
            index=models.Index(fields=['service_date'], name='billing_ser_service_e59cad_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceline',
            index=models.Index(fields=['procedure_code'], name='billing_ser_procedu_966e8b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='claimline',
            unique_together={('claim', 'line_number')},
        ),
    ]
