# Generated by Django 5.2.14 on 2026-10-05 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_initial'),
        ('clinic', '0001_initial'),
        ('core', '0001_initial'),
        ('orders', '0004_examorder_appointment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceline',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_lines', to='clinic.encounter'),
        ),
        migrations.AlterField(
            model_name='serviceline',
            name='exam_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_lines', to='orders.examorder'),
        ),
        migrations.AddConstraint(
            model_name='serviceline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('encounter__isnull', True), ('exam_order__isnull', False)), models.Q(('encounter__isnull', False), ('exam_order__isnull', True)), _connector='OR'), name='billing_serviceline_source_exclusive'),
        ),
    ]
