# Generated by Django 5.2.14 on 2026-05-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_alter_tenant_schema_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='schema_name',
            field=models.CharField(max_length=63, unique=True),
        ),
    ]
