# Generated by Django 6.0.5 on 2026-05-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_alter_tenant_schema_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='license_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='license_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='license_signature',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
