# Generated by Django 6.0.5 on 2026-05-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_device_updated_at_modality_alter_device_modality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modality',
            name='code',
            field=models.CharField(choices=[('AU', 'Audio'), ('BD', 'Biomagnetic Device'), ('BI', 'Biosignal'), ('CD', 'Confocal Microscopy'), ('CR', 'Computed Radiography'), ('CT', 'Computed Tomography'), ('DG', 'Diaphanography'), ('DX', 'Digital Radiography'), ('ECG', 'Electrocardiography'), ('EPS', 'Cardiac Electrophysiology'), ('ES', 'Endoscopy'), ('FID', 'Fiducials'), ('GM', 'General Microscopy'), ('HC', 'Hard Copy'), ('HD', 'Hemodynamic Waveform'), ('IO', 'Intra-oral Radiography'), ('IVUS', 'Intravascular Ultrasound'), ('KO', 'Key Object Selection'), ('LS', 'Laser Surface Scan'), ('MG', 'Mammography'), ('MR', 'Magnetic Resonance'), ('NM', 'Nuclear Medicine'), ('OP', 'Ophthalmic Photography'), ('OPM', 'Ophthalmic Mapping'), ('OPT', 'Ophthalmic Tomography'), ('OSS', 'Optical Surface Scan'), ('OT', 'Other'), ('PX', 'Panoramic X-Ray'), ('PT', 'Positron Emission Tomography'), ('RG', 'Radiographic Imaging'), ('RF', 'Radio Fluoroscopy'), ('RTDOSE', 'Radiotherapy Dose'), ('RTIMAGE', 'Radiotherapy Image'), ('RTPLAN', 'Radiotherapy Plan'), ('RTRECORD', 'Radiotherapy Record'), ('RTSTRUCT', 'Radiotherapy Structure Set'), ('RWV', 'Real World Value Map'), ('SC', 'Secondary Capture'), ('SM', 'Slide Microscopy'), ('SMR', 'Stereometric Radiography'), ('SR', 'Structured Report'), ('STAIN', 'Staining'), ('TG', 'Thermography'), ('US', 'Ultrasound'), ('VA', 'Visual Acuity'), ('XC', 'External Camera Photography'), ('XA', 'X-Ray Angiography')], max_length=10),
        ),
        migrations.AlterField(
            model_name='modality',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
