# Generated by Django 6.0.7 on 2026-07-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_device_updated_at_modality_alter_device_modality'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='license_max_orders',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of orders allowed by license (null for unlimited)', null=True),
        ),
    ]
