# Generated by Django 5.2.14 on 2026-06-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0009_device_dicom_ae_title_dicom_host_dicom_port"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="dicom_host",
            field=models.GenericIPAddressField(
                help_text="IP address or hostname of the DICOM device",
                default="127.0.0.1",
            ),
        ),
    ]
