# Generated by Django 5.2.14 on 2026-06-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_alter_device_dicom_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='dicom_host',
            field=models.GenericIPAddressField(help_text='IP address or hostname of the DICOM device'),
        ),
    ]
