# Generated by Django 5.2.14 on 2026-07-13 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_tenant_license_max_orders'),
        ('tenants', '0011_alter_device_dicom_host'),
    ]

    operations = [
    ]
