# Generated by Django 6.0.7 on 2026-07-18 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_merge_20260714_0025'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='device',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='facility',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='modality',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='Domain',
        ),
        migrations.RemoveField(
            model_name='device',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='modality',
            name='tenant',
        ),
    ]
