# Generated by Django 6.0.7 on 2026-07-18 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_remove_auditlog_tenant'),
        ('billing', '0003_remove_authorization_billing_aut_tenant__18f5ea_idx_and_more'),
        ('integrations', '0003_remove_hl7messagelog_integration_tenant__8b19c7_idx_and_more'),
        ('orders', '0003_remove_examorder_unique_accession_per_tenant_and_more'),
        ('patients', '0003_remove_patient_unique_mrn_per_tenant_and_more'),
        ('reports', '0003_remove_report_reports_rep_tenant__115329_idx_and_more'),
        ('tenants', '0013_alter_device_unique_together_and_more'),
        ('users', '0002_remove_user_users_user_tenant__b5ba35_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
