# Generated by Django 5.2.14 on 2026-10-05 16:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('start_datetime', models.DateTimeField(db_index=True)),
                ('duration_minutes', models.PositiveIntegerField(default=20)),
                ('status', models.CharField(choices=[('BOOKED', 'Booked'), ('CONFIRMED', 'Confirmed'), ('CHECKED_IN', 'Checked in'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No show')], db_index=True, default='BOOKED', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('cancelled_reason', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_created', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='core.facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='patients.patient')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments_as_provider', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, help_text='Room/station resource; same primitive used by exam scheduling.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='core.device')),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PLANNED', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, help_text='Chief complaint / reason for visit.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounters', to='clinic.appointment')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounters_created', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='core.facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='patients.patient')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encounters_as_provider', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FacilityAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_at_facility', models.CharField(choices=[('ADMIN', 'Administrator'), ('PROVIDER', 'Provider / Physician'), ('RECEPTIONIST', 'Receptionist'), ('TECHNICIAN', 'Technician'), ('BILLING', 'Billing staff')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_assignments', to='core.facility')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['facility__name', 'user__email'],
            },
        ),
        migrations.CreateModel(
            name='PatientFacilityIdentifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=50)),
                ('identifier_type', models.CharField(choices=[('MRN', 'Medical Record Number'), ('CHART', 'Chart number'), ('NATIONAL_ID', 'National ID as captured at site'), ('OTHER', 'Other')], default='MRN', max_length=15)),
                ('is_primary', models.BooleanField(default=True, help_text='Primary chart identifier for this patient at this site.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_identifiers', to='core.facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_identifiers', to='patients.patient')),
            ],
            options={
                'ordering': ['facility__name', 'identifier'],
            },
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['facility', 'start_datetime'], name='clinic_appo_facilit_dd5b44_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['provider', 'start_datetime'], name='clinic_appo_provide_97c2e7_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status'], name='clinic_appo_status_7ffd30_idx'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['facility', 'status'], name='clinic_enco_facilit_19f448_idx'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['patient', 'started_at'], name='clinic_enco_patient_0f3606_idx'),
        ),
        migrations.AddIndex(
            model_name='facilityassignment',
            index=models.Index(fields=['facility', 'is_active'], name='clinic_faci_facilit_76ba54_idx'),
        ),
        migrations.AddIndex(
            model_name='facilityassignment',
            index=models.Index(fields=['user', 'is_active'], name='clinic_faci_user_id_52bdbc_idx'),
        ),
        migrations.AddConstraint(
            model_name='facilityassignment',
            constraint=models.UniqueConstraint(fields=('user', 'facility'), name='unique_user_facility_assignment'),
        ),
        migrations.AddIndex(
            model_name='patientfacilityidentifier',
            index=models.Index(fields=['patient', 'facility'], name='clinic_pati_patient_4d47cd_idx'),
        ),
        migrations.AddConstraint(
            model_name='patientfacilityidentifier',
            constraint=models.UniqueConstraint(fields=('facility', 'identifier_type', 'identifier'), name='unique_site_patient_identifier'),
        ),
        migrations.AddConstraint(
            model_name='patientfacilityidentifier',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('patient', 'facility'), name='unique_primary_identifier_per_site'),
        ),
    ]
