# Generated by Django 5.2.14 on 2026-10-09 15:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
        ('core', '0001_initial'),
        ('orders', '0004_examorder_appointment'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('TEMPLATE', 'Weekly template'), ('EXCEPTION', 'Single-date exception')], default='TEMPLATE', max_length=10)),
                ('weekday', models.PositiveSmallIntegerField(blank=True, help_text='0=Monday … 6=Sunday (Python weekday numbering), template rows only.', null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('exception_date', models.DateField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True, help_text='EXCEPTION rows with False block the whole day (day off / leave).')),
                ('slot_minutes', models.PositiveIntegerField(default=20, help_text='Default appointment length offered in this window.')),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['provider', 'weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField(db_index=True)),
                ('duration_minutes', models.PositiveIntegerField(default=20)),
                ('purpose', models.CharField(blank=True, max_length=100)),
                ('is_cancelled', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='queue_position',
            field=models.PositiveIntegerField(blank=True, help_text='Waiting-queue order within the facility; assigned at check-in.', null=True),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['facility', 'status', 'checked_in_at'], name='clinic_appo_facilit_676e61_idx'),
        ),
        migrations.AddField(
            model_name='provideravailability',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_availabilities', to='core.facility'),
        ),
        migrations.AddField(
            model_name='provideravailability',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='appointment',
            field=models.OneToOneField(blank=True, help_text='Clinic appointment that holds this booking, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_booking', to='clinic.appointment'),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='exam_order',
            field=models.OneToOneField(blank=True, help_text='Radiology order holding this booking via the scheduling adapter.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_booking', to='orders.examorder'),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_bookings', to='core.facility'),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='core.device'),
        ),
        migrations.AddIndex(
            model_name='provideravailability',
            index=models.Index(fields=['provider', 'facility', 'kind'], name='clinic_prov_provide_eb55bb_idx'),
        ),
        migrations.AddIndex(
            model_name='provideravailability',
            index=models.Index(fields=['exception_date'], name='clinic_prov_excepti_0c4460_idx'),
        ),
        migrations.AddConstraint(
            model_name='provideravailability',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'TEMPLATE'), ('start_time__isnull', False), ('weekday__isnull', False)), models.Q(('exception_date__isnull', False), ('kind', 'EXCEPTION')), _connector='OR'), name='provider_avail_template_fields'),
        ),
        migrations.AddIndex(
            model_name='roombooking',
            index=models.Index(fields=['room', 'start_datetime', 'is_cancelled'], name='clinic_room_room_id_fbd1dd_idx'),
        ),
        migrations.AddConstraint(
            model_name='roombooking',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('appointment__isnull', False), ('exam_order__isnull', True)), models.Q(('appointment__isnull', True), ('exam_order__isnull', False)), _connector='OR'), name='room_booking_exactly_one_holder'),
        ),
    ]
