# Generated by Django 5.2.14 on 2026-10-09 16:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_provideravailability_roombooking_and_more'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Drug name (generic preferred)', max_length=200)),
                ('dose', models.CharField(blank=True, max_length=100)),
                ('frequency', models.CharField(blank=True, help_text='e.g., BID, TID, q6h', max_length=100)),
                ('route', models.CharField(blank=True, help_text='e.g., PO, IV, SC', max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('CURRENT', 'Current'), ('PAST', 'Past'), ('STOPPED', 'Stopped')], default='CURRENT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medications_documented', to='clinic.encounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='patients.patient')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medications_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medication_name', models.CharField(max_length=200)),
                ('dose', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('route', models.CharField(blank=True, max_length=50)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('days_supply', models.PositiveIntegerField(blank=True, null=True)),
                ('refills_allowed', models.PositiveSmallIntegerField(default=0)),
                ('instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ISSUED', 'Issued'), ('CANCELLED', 'Cancelled')], default='ISSUED', max_length=10)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='clinic.encounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='patients.patient')),
                ('prescriber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions_issued', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('substance', models.CharField(help_text='e.g., Penicillin, iodinated contrast', max_length=150)),
                ('reaction_type', models.CharField(choices=[('ALLERGIC', 'Allergic'), ('INTOLERANCE', 'Intolerance'), ('UNKNOWN', 'Unknown')], default='ALLERGIC', max_length=15)),
                ('severity', models.CharField(choices=[('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe')], default='MODERATE', max_length=10)),
                ('clinical_status', models.CharField(choices=[('ACTIVE', 'Active'), ('CONFIRMED', 'Confirmed'), ('ENTERED_IN_ERROR', 'Entered in error')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('documented_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('documented_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allergies_documented', to='clinic.encounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='patients.patient')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allergies_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['substance'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('clinical_status__in', ['ACTIVE', 'CONFIRMED'])), fields=('patient', 'substance', 'reaction_type'), name='unique_active_allergy_per_patient_substance')],
            },
        ),
        migrations.CreateModel(
            name='EncounterNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('body', models.TextField()),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('content_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('prev_version_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounter_notes_authored', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='clinic.encounter')),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='clinic.encounternote')),
            ],
            options={
                'ordering': ['encounter', 'version'],
                'constraints': [models.UniqueConstraint(fields=('encounter', 'version'), name='unique_note_version_per_encounter')],
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, help_text='ICD-10-CM code', max_length=10)),
                ('description', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RESOLVED', 'Resolved'), ('HISTORY', 'History'), ('ENTERED_IN_ERROR', 'Entered in error')], default='ACTIVE', max_length=20)),
                ('onset_date', models.DateField(blank=True, null=True)),
                ('resolved_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems', to='clinic.encounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='patients.patient')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('resolved_date__isnull', False), ('status__in', ['RESOLVED', 'HISTORY'])), ('resolved_date__isnull', True), _connector='OR'), name='clinic_problem_resolved_needs_date')],
            },
        ),
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('systolic_bp', models.PositiveIntegerField(blank=True, null=True)),
                ('diastolic_bp', models.PositiveIntegerField(blank=True, null=True)),
                ('heart_rate', models.PositiveIntegerField(blank=True, help_text='bpm', null=True)),
                ('respiratory_rate', models.PositiveIntegerField(blank=True, help_text='breaths/min', null=True)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('spo2_pct', models.DecimalField(blank=True, decimal_places=1, help_text='%', max_digits=4, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='clinic.encounter')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vitals_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['encounter', 'recorded_at'], name='clinic_vita_encount_2392e0_idx')],
            },
        ),
    ]
