# Generated by Django 5.2.14 on 2026-10-09 16:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_encounter_cancellation_reason_medication_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('APPT_BOOKED', 'Appointment booked'), ('APPT_CANCELLED', 'Appointment cancelled'), ('APPT_COMPLETED', 'Appointment completed'), ('ENCOUNTER_CLOSED', 'Encounter closed')], db_index=True, max_length=30)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.UUIDField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_attempts', models.PositiveIntegerField(default=0)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='integration_events', to='core.facility')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='clinic_inte_event_t_0bfab6_idx'), models.Index(fields=['delivered_at'], name='clinic_inte_deliver_14ff96_idx')],
            },
        ),
    ]
