# Generated by Django 5.2.14 on 2026-10-10 12:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_integrationevent'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationevent',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DELIVERED', 'Delivered'), ('FAILED', 'Delivery failed (will retry)'), ('DEAD_LETTER', 'Dead letter (max attempts exceeded)')], db_index=True, default='PENDING', max_length=15),
        ),
        migrations.CreateModel(
            name='PatientMergeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary', models.JSONField(default=dict, help_text='Counts/ids from merge_patients().')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('canonical', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merge_log_as_canonical', to='patients.patient')),
                ('duplicate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merge_log_as_duplicate', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['duplicate'], name='clinic_pati_duplica_51ac3d_idx'), models.Index(fields=['canonical'], name='clinic_pati_canonic_0bc34d_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('duplicate', models.F('canonical')), _negated=True), name='merge_log_distinct_patients')],
            },
        ),
    ]
