# Generated by Django 5.2.17 on 2026-10-01 07:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('orders', '0003_alter_examorder_facility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stocktransaction',
            constraint=models.CheckConstraint(condition=models.Q(('transaction_type__in', ['IN', 'OUT', 'ADJUSTMENT'])), name='stock_transaction_type_valid'),
        ),
    ]
