# Generated by Django 5.2.17 on 2026-10-01 10:09

import django.db.models.deletion
import django.utils.timezone
import inventory.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stocktransaction_stock_transaction_type_valid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('tax_id', models.CharField(blank=True, max_length=60)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='batch_number',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Earliest expiry currently held for this SKU.', null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='manufacture_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StockReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(default=inventory.models.default_receipt_number, max_length=30, unique=True)),
                ('invoice_number', models.CharField(blank=True, max_length=60)),
                ('delivery_note', models.CharField(blank=True, max_length=60)),
                ('received_date', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_receipts', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='inventory.supplier')),
            ],
            options={
                'verbose_name': 'stock receipt',
                'verbose_name_plural': 'stock receipts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Default seller this item is purchased from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.supplier'),
        ),
        migrations.CreateModel(
            name='StockReceiptItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=60)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField()),
                ('minimum_shelf_life_days', models.PositiveIntegerField(default=90, help_text='Deliveries expiring sooner than this are rejected.')),
                ('expiry_status', models.CharField(choices=[('OK', 'Acceptable'), ('WARNING', 'Accepted with warning (short shelf life)'), ('REJECTED', 'Rejected (expired / below minimum shelf life)')], default='OK', max_length=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_items', to='inventory.inventoryitem')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockreceipt')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt_item', to='inventory.stocktransaction')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='stock_receipt_item_quantity_positive')],
            },
        ),
        migrations.AddIndex(
            model_name='stockreceipt',
            index=models.Index(fields=['supplier', 'received_date'], name='inventory_s_supplie_e41f2f_idx'),
        ),
    ]
