# Generated by Django 6.0.7 on 2026-07-18 13:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PRELIMINARY', 'Preliminary'), ('FINAL', 'Final'), ('AMENDED', 'Amended')], db_index=True, default='DRAFT', max_length=20)),
                ('findings_en', models.TextField(blank=True)),
                ('findings_ar', models.TextField(blank=True)),
                ('impression_en', models.TextField(blank=True)),
                ('impression_ar', models.TextField(blank=True)),
                ('critical_finding', models.BooleanField(default=False)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('structured_data', models.JSONField(blank=True, default=dict)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='orders.examorder')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
