# Generated by Django 6.0.7 on 2026-07-18 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='peer_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='radiologist',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', 'finalized_at'], name='reports_rep_status_965de1_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['critical_finding'], name='reports_rep_critica_0f902d_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['is_deleted'], name='reports_rep_is_dele_e80fe5_idx'),
        ),
    ]
