# Generated by Django 5.2.14 on 2026-05-22 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='peer_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='radiologist',
            field=models.ForeignKey(limit_choices_to={'role': 'RADIOLOGIST'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['tenant', 'status', 'finalized_at'], name='reports_rep_tenant__115329_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['tenant', 'critical_finding'], name='reports_rep_tenant__e79eb6_idx'),
        ),
    ]
