# Generated by Django 6.0.7 on 2026-07-18 13:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_examorder_unique_accession_per_tenant_and_more'),
        ('reports', '0002_report_deleted_at_report_is_deleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='report',
            name='reports_rep_tenant__115329_idx',
        ),
        migrations.RemoveIndex(
            model_name='report',
            name='reports_rep_tenant__e79eb6_idx',
        ),
        migrations.RemoveIndex(
            model_name='report',
            name='reports_rep_tenant__c41919_idx',
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', 'finalized_at'], name='reports_rep_status_965de1_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['critical_finding'], name='reports_rep_critica_0f902d_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['is_deleted'], name='reports_rep_is_dele_e80fe5_idx'),
        ),
        migrations.RemoveField(
            model_name='report',
            name='tenant',
        ),
    ]
