# Generated by Django 6.0.7 on 2026-07-18 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='tenant',
        ),
    ]
