# Generated by Django 6.0.7 on 2026-07-18 13:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModalityWorklistEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dicom_query_retrieve_level', models.CharField(default='PATIENT', max_length=20)),
                ('last_mwl_sync', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(default='PENDING', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HL7MessageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(db_index=True, max_length=10)),
                ('direction', models.CharField(choices=[('IN', 'Inbound'), ('OUT', 'Outbound')], max_length=10)),
                ('raw_content', models.TextField()),
                ('status', models.CharField(default='RECEIVED', max_length=20)),
                ('error_details', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['message_type', 'received_at'], name='integration_message_5c71ff_idx')],
            },
        ),
    ]
