# Generated by Django 5.2.14 on 2026-05-22 22:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModalityWorklistEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dicom_query_retrieve_level', models.CharField(default='PATIENT', max_length=20)),
                ('last_mwl_sync', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(default='PENDING', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HL7MessageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(db_index=True, max_length=10)),
                ('direction', models.CharField(choices=[('IN', 'Inbound'), ('OUT', 'Outbound')], max_length=10)),
                ('raw_content', models.TextField()),
                ('status', models.CharField(default='RECEIVED', max_length=20)),
                ('error_details', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
