# Generated by Django 6.0.7 on 2026-07-18 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modalityworklistentry',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mwl_entry', to='orders.examorder'),
        ),
        migrations.AddIndex(
            model_name='modalityworklistentry',
            index=models.Index(fields=['sync_status'], name='integration_sync_st_d9a4ab_idx'),
        ),
    ]
