# Generated by Django 5.2.14 on 2026-05-22 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0001_initial'),
        ('orders', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modalityworklistentry',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mwl_entry', to='orders.examorder'),
        ),
        migrations.AddField(
            model_name='modalityworklistentry',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='hl7messagelog',
            index=models.Index(fields=['tenant', 'message_type', 'received_at'], name='integration_tenant__8b19c7_idx'),
        ),
        migrations.AddIndex(
            model_name='modalityworklistentry',
            index=models.Index(fields=['tenant', 'sync_status'], name='integration_tenant__a5929e_idx'),
        ),
    ]
