# Generated by Django 6.0.7 on 2026-07-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_initial'),
        ('orders', '0002_examorder_deleted_at_examorder_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='hl7messagelog',
            name='integration_tenant__8b19c7_idx',
        ),
        migrations.RemoveIndex(
            model_name='modalityworklistentry',
            name='integration_tenant__a5929e_idx',
        ),
        migrations.AddIndex(
            model_name='hl7messagelog',
            index=models.Index(fields=['message_type', 'received_at'], name='integration_message_5c71ff_idx'),
        ),
        migrations.AddIndex(
            model_name='modalityworklistentry',
            index=models.Index(fields=['sync_status'], name='integration_sync_st_d9a4ab_idx'),
        ),
        migrations.RemoveField(
            model_name='hl7messagelog',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='modalityworklistentry',
            name='tenant',
        ),
    ]
