# Generated by Django 6.0.7 on 2026-07-18 13:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mrn', models.CharField(db_index=True, max_length=50)),
                ('first_name_en', models.CharField(max_length=100)),
                ('last_name_en', models.CharField(max_length=100)),
                ('first_name_ar', models.CharField(blank=True, max_length=100)),
                ('last_name_ar', models.CharField(blank=True, max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('nationality', models.CharField(blank=True, max_length=3)),
                ('national_id', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=30)),
                ('insurance_provider', models.CharField(blank=True, max_length=150)),
                ('insurance_policy_number', models.CharField(blank=True, max_length=100)),
                ('is_deceased', models.BooleanField(default=False)),
                ('consent_data_sharing', models.BooleanField(default=False)),
                ('data_retention_until', models.DateField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['last_name_en', 'first_name_en'], name='patients_pa_last_na_b55702_idx'), models.Index(fields=['national_id'], name='patients_pa_nationa_70cc77_idx'), models.Index(fields=['is_deleted'], name='patients_pa_is_dele_2885d0_idx')],
                'constraints': [models.UniqueConstraint(fields=('mrn',), name='unique_mrn')],
            },
        ),
    ]
