# Generated by Django 5.2.14 on 2026-07-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('tenants', '0012_merge_20260714_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['tenant', 'is_deleted'], name='patients_pa_tenant__a1aced_idx'),
        ),
    ]
