# Generated by Django 6.0.7 on 2026-07-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_deleted_at_patient_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='patient',
            name='unique_mrn_per_tenant',
        ),
        migrations.RemoveIndex(
            model_name='patient',
            name='patients_pa_tenant__a74c33_idx',
        ),
        migrations.RemoveIndex(
            model_name='patient',
            name='patients_pa_tenant__d2d66d_idx',
        ),
        migrations.RemoveIndex(
            model_name='patient',
            name='patients_pa_tenant__a1aced_idx',
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['last_name_en', 'first_name_en'], name='patients_pa_last_na_b55702_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['national_id'], name='patients_pa_nationa_70cc77_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['is_deleted'], name='patients_pa_is_dele_2885d0_idx'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(fields=('mrn',), name='unique_mrn'),
        ),
        migrations.RemoveField(
            model_name='patient',
            name='tenant',
        ),
    ]
