# Generated by Django 5.2.14 on 2026-06-04 21:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('tenants', '0008_alter_modality_code_alter_modality_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name_en', models.CharField(max_length=150)),
                ('name_ar', models.CharField(blank=True, max_length=150)),
                ('modality_type', models.CharField(choices=[('CT', 'CT'), ('MR', 'MR'), ('XR', 'X-Ray'), ('US', 'Ultrasound'), ('NM', 'Nuclear Medicine'), ('PET', 'PET'), ('FLUORO', 'Fluoroscopy'), ('INT', 'Interventional'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['modality_type', 'code'],
                'indexes': [models.Index(fields=['modality_type', 'is_active'], name='orders_proc_modalit_89f320_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExamOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accession_number', models.CharField(db_index=True, max_length=50)),
                ('referring_physician', models.CharField(blank=True, max_length=150)),
                ('procedure_code', models.CharField(max_length=20)),
                ('procedure_name_en', models.CharField(max_length=150)),
                ('procedure_name_ar', models.CharField(blank=True, max_length=150)),
                ('priority', models.CharField(choices=[('STAT', 'Stat'), ('URGENT', 'Urgent'), ('ROUTINE', 'Routine')], default='ROUTINE', max_length=10)),
                ('clinical_indication', models.TextField(blank=True)),
                ('laterality', models.CharField(blank=True, choices=[('L', 'Left'), ('R', 'Right'), ('B', 'Bilateral')], max_length=3)),
                ('body_part', models.CharField(blank=True, max_length=100)),
                ('contrast_required', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('REPORTED', 'Reported'), ('FINALIZED', 'Finalized'), ('CANCELLED', 'Cancelled')], db_index=True, default='REGISTERED', max_length=20)),
                ('scheduled_datetime', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=15)),
                ('dicom_study_instance_uid', models.CharField(blank=True, db_index=True, max_length=64)),
                ('hl7_message_control_id', models.CharField(blank=True, max_length=100)),
                ('billing_status', models.CharField(db_index=True, default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.facility')),
                ('modality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_orders', to='tenants.modality')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.patient')),
                ('room_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_orders', to='tenants.device')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['-scheduled_datetime'],
                'indexes': [models.Index(fields=['tenant', 'status', 'scheduled_datetime'], name='orders_exam_tenant__7258f3_idx'), models.Index(fields=['tenant', 'modality', 'priority'], name='orders_exam_tenant__a4ed98_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'accession_number'), name='unique_accession_per_tenant')],
            },
        ),
    ]
