# Generated by Django 5.2.14 on 2026-05-22 22:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accession_number', models.CharField(db_index=True, max_length=50)),
                ('referring_physician', models.CharField(blank=True, max_length=150)),
                ('modality', models.CharField(choices=[('CT', 'CT'), ('MR', 'MRI'), ('XR', 'X-Ray'), ('US', 'Ultrasound'), ('NM', 'Nuclear'), ('DX', 'Digital X-Ray')], max_length=3)),
                ('procedure_code', models.CharField(max_length=20)),
                ('procedure_name_en', models.CharField(max_length=150)),
                ('procedure_name_ar', models.CharField(blank=True, max_length=150)),
                ('priority', models.CharField(choices=[('STAT', 'Stat'), ('URGENT', 'Urgent'), ('ROUTINE', 'Routine')], default='ROUTINE', max_length=10)),
                ('clinical_indication', models.TextField(blank=True)),
                ('laterality', models.CharField(blank=True, choices=[('L', 'Left'), ('R', 'Right'), ('B', 'Bilateral')], max_length=3)),
                ('body_part', models.CharField(blank=True, max_length=100)),
                ('contrast_required', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('REPORTED', 'Reported'), ('FINALIZED', 'Finalized'), ('CANCELLED', 'Cancelled')], db_index=True, default='REGISTERED', max_length=20)),
                ('scheduled_datetime', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=15)),
                ('room_station', models.CharField(blank=True, max_length=50)),
                ('dicom_study_instance_uid', models.CharField(blank=True, db_index=True, max_length=64)),
                ('hl7_message_control_id', models.CharField(blank=True, max_length=100)),
                ('billing_status', models.CharField(db_index=True, default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-scheduled_datetime'],
            },
        ),
    ]
