# Generated by Django 5.2.14 on 2026-07-17 19:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('patients', '0001_initial'),
        ('tenants', '0012_merge_20260714_0025'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examorder',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examorder',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='examorder',
            index=models.Index(fields=['tenant', 'is_deleted'], name='orders_exam_tenant__f2f698_idx'),
        ),
    ]
