# Generated by Django 6.0.7 on 2026-07-18 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('patients', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examorder',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examorder',
            name='facility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.facility'),
        ),
        migrations.AddField(
            model_name='examorder',
            name='modality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_orders', to='tenants.modality'),
        ),
        migrations.AddField(
            model_name='examorder',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.patient'),
        ),
        migrations.AddField(
            model_name='examorder',
            name='room_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_orders', to='tenants.device'),
        ),
        migrations.AddIndex(
            model_name='procedure',
            index=models.Index(fields=['modality_type', 'is_active'], name='orders_proc_modalit_89f320_idx'),
        ),
        migrations.AddIndex(
            model_name='examorder',
            index=models.Index(fields=['status', 'scheduled_datetime'], name='orders_exam_status_8e7651_idx'),
        ),
        migrations.AddIndex(
            model_name='examorder',
            index=models.Index(fields=['modality', 'priority'], name='orders_exam_modalit_672480_idx'),
        ),
        migrations.AddIndex(
            model_name='examorder',
            index=models.Index(fields=['is_deleted'], name='orders_exam_is_dele_f154a8_idx'),
        ),
        migrations.AddConstraint(
            model_name='examorder',
            constraint=models.UniqueConstraint(fields=('accession_number',), name='unique_accession_number'),
        ),
    ]
