# Generated by Django 5.2.14 on 2026-05-22 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('patients', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examorder',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examorder',
            name='facility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.facility'),
        ),
        migrations.AddField(
            model_name='examorder',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.patient'),
        ),
        migrations.AddField(
            model_name='examorder',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='examorder',
            index=models.Index(fields=['tenant', 'status', 'scheduled_datetime'], name='orders_exam_tenant__7258f3_idx'),
        ),
        migrations.AddIndex(
            model_name='examorder',
            index=models.Index(fields=['tenant', 'modality', 'priority'], name='orders_exam_tenant__18d97b_idx'),
        ),
        migrations.AddConstraint(
            model_name='examorder',
            constraint=models.UniqueConstraint(fields=('tenant', 'accession_number'), name='unique_accession_per_tenant'),
        ),
    ]
