# Generated by Django 6.0.5 on 2026-05-28 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        ('tenants', '0007_device_updated_at_modality_alter_device_modality'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='examorder',
            new_name='orders_exam_tenant__a4ed98_idx',
            old_name='orders_exam_tenant__18d97b_idx',
        ),
        migrations.AlterField(
            model_name='examorder',
            name='modality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_orders', to='tenants.modality'),
        ),
    ]
