# Generated by Django 6.0.7 on 2026-07-18 12:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_examorder_deleted_at_examorder_is_deleted_and_more'),
        ('patients', '0003_remove_patient_unique_mrn_per_tenant_and_more'),
        ('tenants', '0012_merge_20260714_0025'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='examorder',
            name='unique_accession_per_tenant',
        ),
        migrations.RemoveIndex(
            model_name='examorder',
            name='orders_exam_tenant__7258f3_idx',
        ),
        migrations.RemoveIndex(
            model_name='examorder',
            name='orders_exam_tenant__a4ed98_idx',
        ),
        migrations.RemoveIndex(
            model_name='examorder',
            name='orders_exam_tenant__f2f698_idx',
        ),
        migrations.AddIndex(
            model_name='examorder',
            index=models.Index(fields=['status', 'scheduled_datetime'], name='orders_exam_status_8e7651_idx'),
        ),
        migrations.AddIndex(
            model_name='examorder',
            index=models.Index(fields=['modality', 'priority'], name='orders_exam_modalit_672480_idx'),
        ),
        migrations.AddIndex(
            model_name='examorder',
            index=models.Index(fields=['is_deleted'], name='orders_exam_is_dele_f154a8_idx'),
        ),
        migrations.AddConstraint(
            model_name='examorder',
            constraint=models.UniqueConstraint(fields=('accession_number',), name='unique_accession_number'),
        ),
        migrations.RemoveField(
            model_name='examorder',
            name='tenant',
        ),
    ]
