# Generated by Django 5.2.14 on 2026-10-05 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
        ('orders', '0003_alter_examorder_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='examorder',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_orders', to='clinic.appointment'),
        ),
    ]
