# Generated by Django 6.0.5 on 2026-05-28 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_orders_exam_tenant__18d97b_idx_orders_exam_tenant__a4ed98_idx_and_more'),
        ('tenants', '0007_device_updated_at_modality_alter_device_modality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examorder',
            name='room_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_orders', to='tenants.device'),
        ),
    ]
