# Generated by Django 6.0.5 on 2026-05-30 09:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_procedure_code_choices'),
        ('tenants', '0008_alter_modality_code_alter_modality_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('CT', 'Computed Tomography'), ('MR', 'Magnetic Resonance'), ('XR', 'X-Ray'), ('US', 'Ultrasound'), ('NM', 'Nuclear Medicine'), ('PT', 'Positron Emission Tomography'), ('FLUORO', 'Fluoroscopy'), ('INT', 'Interventional'), ('OT', 'Other')], default='OT', max_length=20)),
                ('body_part', models.CharField(blank=True, max_length=100)),
                ('laterality', models.CharField(choices=[('L', 'Left'), ('R', 'Right'), ('B', 'Bilateral'), ('N', 'Not Applicable')], default='N', max_length=3)),
                ('contrast_options', models.CharField(choices=[('NONE', 'No Contrast'), ('WITH', 'With Contrast'), ('WITHOUT', 'Without Contrast'), ('WITH_WITHOUT', 'With and Without Contrast')], default='NONE', max_length=20)),
                ('default_units', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('revenue_code', models.CharField(blank=True, help_text='UB-04 revenue code', max_length=4)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedures', to='tenants.modality')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='tenants.tenant')),
            ],
            options={
                'ordering': ['code'],
                'indexes': [models.Index(fields=['tenant', 'category'], name='orders_proc_tenant__729049_idx'), models.Index(fields=['tenant', 'is_active'], name='orders_proc_tenant__c71a5e_idx')],
                'unique_together': {('tenant', 'code')},
            },
        ),
    ]
