# Generated by Django 6.0.5 on 2026-05-30 10:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_procedure_code_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name_en', models.CharField(max_length=150)),
                ('name_ar', models.CharField(blank=True, max_length=150)),
                ('modality_type', models.CharField(choices=[('CT', 'CT'), ('MR', 'MR'), ('XR', 'X-Ray'), ('US', 'Ultrasound'), ('NM', 'Nuclear Medicine'), ('PET', 'PET'), ('FLUORO', 'Fluoroscopy'), ('INT', 'Interventional'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['modality_type', 'code'],
                'indexes': [models.Index(fields=['modality_type', 'is_active'], name='orders_proc_modalit_89f320_idx')],
            },
        ),
    ]
