# Generated by Django 6.0.5 on 2026-05-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_procedure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examorder',
            name='procedure_code',
            field=models.CharField(max_length=20),
        ),
    ]
